import {
  Button,
  DataGrid,
  DataGridBody,
  DataGridCell,
  DataGridHeader,
  DataGridHeaderCell,
  DataGridRow,
  TableCellLayout,
  TableColumnDefinition,
  Text,
  createTableColumn,
} from "@fluentui/react-components";
import { EditRegular, DeleteRegular, OpenRegular } from "@fluentui/react-icons";
import { useEffect, useRef, useState } from "react";
// import { useNavigate } from "react-router-dom";
// import { getWorkOrders } from "../services/workOrderServices";
// import { useSetAtom } from "jotai";
// import { errorMessageAtom, isInProgressAtom } from "../atoms/messageBarAtoms";

type Item = {
  id: number;
  note: string;
  createdDate: Date;
};

const columns: TableColumnDefinition<Item>[] = [
  createTableColumn<Item>({
    columnId: "id",
    compare: (a, b) => {
      return a.id - b.id;
    },
    renderHeaderCell: () => {
      return "Id";
    },
    renderCell: (item) => {
      return <TableCellLayout truncate>{item.id}</TableCellLayout>;
    },
  }),
  createTableColumn<Item>({
    columnId: "note",
    compare: (a, b) => {
      return a.note.localeCompare(b.note);
    },
    renderHeaderCell: () => {
      return "Note";
    },
    renderCell: (item) => {
      return <TableCellLayout truncate>{item.note}</TableCellLayout>;
    },
  }),
  createTableColumn<Item>({
    columnId: "date",
    compare: (a, b) => {
      return a.createdDate.getDate() - b.createdDate.getDate();
    },
    renderHeaderCell: () => {
      return "Created date";
    },
    renderCell: (item) => {
      return (
        <TableCellLayout truncate>
          {item.createdDate.toLocaleString()}
        </TableCellLayout>
      );
    },
  }),
  createTableColumn<Item>({
    columnId: "actions",
    renderHeaderCell: () => {
      return "Actions";
    },
    renderCell: () => {
      return (
        <>
          <Button aria-label="Open" icon={<OpenRegular />} />
          <Button aria-label="Edit" icon={<EditRegular />} />
          <Button aria-label="Delete" icon={<DeleteRegular />} />
        </>
      );
    },
  }),
];

const columnSizingOptions = {
  id: {
    minWidth: 80,
    defaultWidth: 120,
  },
  note: {
    defaultWidth: 180,
    minWidth: 120,
    idealWidth: 180,
  },
};

const WorkOrders = () => {
  // const navigate = useNavigate();
  const [items, setItems] = useState<Item[]>([]);
  const [selectedWorkOrderId, setSelectedWorkOrderId] = useState<number>();
  // const setErrorMessage = useSetAtom(errorMessageAtom);
  // const setIsInProgress = useSetAtom(isInProgressAtom);

  const fetchData = async () => {
    const abortController = new AbortController();
    // setIsInProgress(true);

    try {
      const abortController = new AbortController();

      // const woStatuses: IWorkOrderStatuses[] = await getWorkOrderStatuses(
      //   abortController
      // );
      // setWorkOrderStatuses(woStatuses);
      // clearMessage();

      // const workOrders = await getWorkOrders(abortController, 10, 1);
      const workOrders = {
        items: [
          {
            uuid: "ed083c49-6b19-426e-89bf-d6c3b5a378eb",
            code: "FMS0000044",
            rowStamp: "",
            assetId: 6,
            description:
              "Generated by FMS [Comment: Issue 9:26pm, 18th Dec] [I46-Z3]",
            status: "WAPPR",
            statusId: 5,
            statusDescription:
              "Status of WAPPR can not be found in _maximoToCrmStatusMapping",
            issueId: 46,
            zoneId: 3,
            assetCatId: null,
            zoneName: "DC-B",
            assetCategory: null,
            id: 44,
            createdAt: "2023-12-18T10:26:51.84",
            modifiedAt: "2023-12-22T01:34:51.277",
            createdBy: 0,
            modifiedBy: null,
            tenantId: null,
          },
          {
            uuid: "84cee18f-925d-4037-9364-6e289448944d",
            code: "FMS0000043",
            rowStamp: "",
            assetId: 5,
            description:
              "Generated by FMS [Comment: Issue 9:25pm, 18th Dec] [I45-Z2]",
            status: "WAPPR",
            statusId: 7,
            statusDescription:
              "Status of WAPPR can not be found in _maximoToCrmStatusMapping",
            issueId: 45,
            zoneId: 2,
            assetCatId: null,
            zoneName: "DC-A",
            assetCategory: null,
            id: 43,
            createdAt: "2023-12-18T10:25:28.013",
            modifiedAt: "2023-12-22T01:35:41.487",
            createdBy: 0,
            modifiedBy: null,
            tenantId: null,
          },
          {
            uuid: "b7c4608d-2277-4822-b7dd-fb55f3e8f8a1",
            code: "FMS0000042",
            rowStamp: "",
            assetId: null,
            description: "WorkOrder by UI - 7",
            status: "WAPPR",
            statusId: 5,
            statusDescription:
              "Status of WAPPR can not be found in _maximoToCrmStatusMapping",
            issueId: 40,
            zoneId: 2,
            assetCatId: null,
            zoneName: "DC-A",
            assetCategory: null,
            id: 42,
            createdAt: "2023-12-17T21:21:02.44",
            modifiedAt: "2023-12-21T20:56:23.01",
            createdBy: 0,
            modifiedBy: null,
            tenantId: null,
          },
          {
            uuid: "f1d607e2-21b3-4111-be0d-299e74bbc8f4",
            code: "FMS0000041",
            rowStamp: "",
            assetId: null,
            description: "WorkOrder by UI - 6",
            status: "WAPPR",
            statusId: 6,
            statusDescription:
              "Status of WAPPR can not be found in _maximoToCrmStatusMapping",
            issueId: 44,
            zoneId: null,
            assetCatId: null,
            zoneName: null,
            assetCategory: null,
            id: 41,
            createdAt: "2023-12-17T19:42:48.92",
            modifiedAt: "2023-12-23T08:42:53.87",
            createdBy: 0,
            modifiedBy: null,
            tenantId: null,
          },
          {
            uuid: "dfdb242b-40fd-43f8-a189-a754e1fbd384",
            code: "FMS0000040",
            rowStamp: "",
            assetId: 5,
            description: "WorkOrder by UI - 5",
            status: "WAPPR",
            statusId: 5,
            statusDescription:
              "Status of WAPPR can not be found in _maximoToCrmStatusMapping",
            issueId: 44,
            zoneId: 2,
            assetCatId: null,
            zoneName: "DC-A",
            assetCategory: null,
            id: 40,
            createdAt: "2023-12-17T19:39:14.397",
            modifiedAt: "2023-12-23T08:13:55.763",
            createdBy: 0,
            modifiedBy: null,
            tenantId: null,
          },
          {
            uuid: "20c6d98f-a14f-44ee-b834-a85a5b131761",
            code: "FMS0000039",
            rowStamp: "",
            assetId: 5,
            description: "WorkOrder by UI -4",
            status: "WAPPR",
            statusId: 5,
            statusDescription:
              "Status of WAPPR can not be found in _maximoToCrmStatusMapping",
            issueId: 33,
            zoneId: 2,
            assetCatId: null,
            zoneName: "DC-A",
            assetCategory: null,
            id: 39,
            createdAt: "2023-12-17T19:15:31.43",
            modifiedAt: "2023-12-23T08:14:02.557",
            createdBy: 0,
            modifiedBy: null,
            tenantId: null,
          },
          {
            uuid: "b4fa53cd-f033-4570-a6f3-ad8b27cfd282",
            code: "FMS0000038",
            rowStamp: "",
            assetId: null,
            description: "WorkOrder by UI -3",
            status: "WAPPR",
            statusId: 7,
            statusDescription:
              "Status of WAPPR can not be found in _maximoToCrmStatusMapping",
            issueId: 33,
            zoneId: 2,
            assetCatId: null,
            zoneName: "DC-A",
            assetCategory: null,
            id: 38,
            createdAt: "2023-12-17T19:07:24.25",
            modifiedAt: "2023-12-23T08:43:04.243",
            createdBy: 0,
            modifiedBy: null,
            tenantId: null,
          },
          {
            uuid: "cad262a4-7c5b-4f99-b442-555db3ad56fe",
            code: "FMS0000037",
            rowStamp: "",
            assetId: null,
            description: "WorkOrder by UI - 2",
            status: "WAPPR",
            statusId: 5,
            statusDescription:
              "Status of WAPPR can not be found in _maximoToCrmStatusMapping",
            issueId: 33,
            zoneId: null,
            assetCatId: null,
            zoneName: null,
            assetCategory: null,
            id: 37,
            createdAt: "2023-12-17T18:48:49.38",
            modifiedAt: "2023-12-23T08:14:19.12",
            createdBy: 0,
            modifiedBy: null,
            tenantId: null,
          },
          {
            uuid: "85329b9f-55c2-48c3-bb90-63f88f0d1956",
            code: "FMS0000036",
            rowStamp: "",
            assetId: null,
            description: "WorkOrder by UI",
            status: "WAPPR",
            statusId: 6,
            statusDescription:
              "Status of WAPPR can not be found in _maximoToCrmStatusMapping",
            issueId: 33,
            zoneId: null,
            assetCatId: null,
            zoneName: null,
            assetCategory: null,
            id: 36,
            createdAt: "2023-12-17T11:40:17.207",
            modifiedAt: "2023-12-23T11:15:14.217",
            createdBy: 0,
            modifiedBy: null,
            tenantId: null,
          },
          {
            uuid: "a7304ca8-177c-440b-9cdf-4bd2025c952b",
            code: "FMS0000035",
            rowStamp: "",
            assetId: null,
            description: "Generated using API - 1",
            status: "WAPPR",
            statusId: 1,
            statusDescription: "Waiting on approval",
            issueId: 33,
            zoneId: null,
            assetCatId: null,
            zoneName: null,
            assetCategory: null,
            id: 35,
            createdAt: "2023-12-17T08:12:24.053",
            modifiedAt: "2023-12-17T08:12:24.053",
            createdBy: 0,
            modifiedBy: null,
            tenantId: null,
          },
        ],
        pageNo: 1,
        pageSize: 10,
        rowsCount: 41,
        pageCount: 5,
        isLastPage: false,
        orderBy: null,
      };

      setItems(
        workOrders.items.map((wo) => ({
          id: wo.id,
          note: wo.description,
          createdDate: new Date(wo.createdAt),
        }))
      );
    } catch (error: any) {
      // setErrorMessage(error.message);
    } finally {
      // setIsInProgress(false);
    }
    return () => {
      abortController.abort();
    };
  };

  useEffect(() => {
    fetchData();
  }, []);
  return (
    <>
      <>
        <Button
          appearance="secondary"
          // onClick={() => navigate("/")}
        >
          Back
        </Button>
        <Text size={500}>WorkOrders</Text>
      </>
      <div style={{ overflowX: "auto" }}>
        <DataGrid
          items={items}
          columns={columns}
          sortable
          selectionMode="single"
          getRowId={(item) => item.Id}
          onSelectionChange={(e, data) =>
            setSelectedWorkOrderId(
              data.selectedItems[0] && data.selectedItems[0].Id
            )
          }
          resizableColumns
          columnSizingOptions={columnSizingOptions}
        >
          <DataGridHeader>
            <DataGridRow
              selectionCell={{
                checkboxIndicator: { "aria-label": "Select all rows" },
              }}
            >
              {({ renderHeaderCell }) => (
                <DataGridHeaderCell>{renderHeaderCell()}</DataGridHeaderCell>
              )}
            </DataGridRow>
          </DataGridHeader>
          <DataGridBody<Item>>
            {({ item, rowId }) => (
              <DataGridRow<Item>
                key={rowId}
                selectionCell={{
                  checkboxIndicator: { "aria-label": "Select row" },
                }}
              >
                {({ renderCell }) => (
                  <DataGridCell>{renderCell(item)}</DataGridCell>
                )}
              </DataGridRow>
            )}
          </DataGridBody>
        </DataGrid>
      </div>
    </>
  );
};

export default WorkOrders;
